# schema.yml
version: 2

sources: 
  - name: raw 
    schema: gz_raw_data
    tables:
      - name: sales
        identifier: raw_gz_sales
        description: sales of Greenweez / we have on row per product_id found in each orders_id
        
        loaded_at_field: "CAST(date_date AS TIMESTAMP)"
        freshness: 
          warn_after:
            count: 90
            period: day
        
        columns:
          - name: date_date
            description: date of purchase
          - name: orders_id
            description: order id of the transaction this product sale was part off
          - name: pdt_id
            description: the products id of each product in each order
          - name: revenue
            description: The revuenue from this product sale, in this order
          - name: quantity
            description: The quantity of this products sold in this order
        tests:
          - unique:
              column_name: "(orders_id || '-' || pdt_id)"
          
      - name: product 
        identifier: raw_gz_product 
        description: products of Greenweez / we have on row per product along with the cost per product
        columns:
          - name: products_id
            description: The unique id for each product
            tests:
              - unique
              - not_null
          - name: purchSE_PRICE
            description: The price for each product

      - name: ship
        identifier: raw_gz_ship
        description: products of Greenweez / we have on row per order along with the shipping & logistal costs for each order
        columns:
          - name: orders_id
            description: The unique id for each order shipped
            tests:
              - unique
              - not_null
          - name: shipping_fee
            description: The fee charged for shipping
          - name: shipping_fee_1
            description: The fee charged for shipping - Duplicate
          - name: log_cost
            description: The logistics costs for each order
          - name: ship_cost
            description: The cost to ship each order

models:
  - name: int_orders_margin
    description: Calculate the margin per order
    columns:
      - name: orders_id
        description: Unique Order Id
        tests:
          - unique
          - not_null
      - name: date_date
        description: Date of each order
      - name: revenue
        description: Revenue for each order
      - name: quantity
        description: quantity of items for each order
      - name: purchase_cost,
        description: Purchase Cost for each order
      - name: margin      
        description: Profit margin for each order 

  - name: int_orders_operational
    description: Calculate the operational margin per order
    columns:
      - name: orders_id
        description: Unique Order Id
        tests:
          - unique
          - not_null
      - name: date_date
        description: Date of last order
      - name: operational_margin
        description: Operational margin for each order
      - name: revenue
        description: The revenue for each order
      - name: purchase_cost,
        description: Purchase Cost for each order
      - name: margin      
        description: Profit margin for each order  
      - name: shipping_fee      
        description: The shipping fee charged for each order  
      - name: log_cost      
        description: The logistical costs for each order

  - name: int_sales_margin
    description: Calculate the margin per product per order
    columns:
      - name: date_date
        description: Date of last order
      - name: orders_id
        description: Order Id
      - name: products_id
        description: The unique id for each product
      - name: quantity
        description: quantity of items for each order
      - name: purchase_cost,
        description: Purchase Cost for each order
      - name: revenue
        description: The revenue for each order
      - name: margin      
        description: Profit margin for each order 
    tests:
      - unique:
          column_name: "(orders_id || '-' || products_id)"

  - name: finance_days
    description: An aggregation of the data providing daily statistics
    columns:
      - name: date_date
        description: The date for each row
        tests:
          - unique
          - not_null         
      - name: nb_transactions
        description: The number of daily transactions
      - name: revenue
        description: Daily revenue
      - name: average_basket
        description: Average basket value
      - name: margin
        description: Daily profit margin
      - name: operational_margin
        description: Daily operational_margin
      - name: purchase_cost
        description: Total daily purchase costs
      - name: shipping_fee
        description: Total daily shipping fees
      - name: log_cost
        description: Total daily logistical costs
      - name: quantity
        description: Total number of items sold each day